import { Anime } from './types';

export const animeDatabase: Anime[] = [
  {
    id: 1,
    title: "Attack on Titan",
    japanese: "進撃の巨人",
    poster: "https://picsum.photos/seed/aot-poster/300/450",
    banner: "https://picsum.photos/seed/aot-banner/1200/400",
    rating: 9.0,
    year: 2013,
    status: "Completed",
    episodes: 87,
    duration: "24 min",
    genre: ["Action", "Drama", "Fantasy"],
    description: "Humanity fights for survival against giant humanoid Titans. When a colossal Titan breaches their wall, Eren Yeager joins the Survey Corps to fight back.",
    trending: true,
    featured: true,
    subs: 87,
    dubs: 87,
    type: 'TV Series'
  },
  {
    id: 2,
    title: "Demon Slayer",
    japanese: "鬼滅の刃",
    poster: "https://picsum.photos/seed/ds-poster/300/450",
    banner: "https://picsum.photos/seed/ds-banner/1200/400",
    rating: 8.7,
    year: 2019,
    status: "Ongoing",
    episodes: 44,
    duration: "23 min",
    genre: ["Action", "Supernatural", "Historical"],
    description: "After his family is slaughtered by demons, Tanjiro Kamado embarks on a dangerous journey to turn his demon sister back into a human.",
    trending: true,
    featured: false,
    subs: 44,
    dubs: 44,
    type: 'TV Series'
  },
  {
    id: 3,
    title: "One Piece",
    japanese: "ワンピース",
    poster: "https://picsum.photos/seed/op-poster/300/450",
    banner: "https://picsum.photos/seed/op-banner/1200/400",
    rating: 9.2,
    year: 1999,
    status: "Ongoing",
    episodes: 1075,
    duration: "24 min",
    genre: ["Adventure", "Comedy", "Shounen"],
    description: "Follow Monkey D. Luffy and his Straw Hat Pirates as they explore the Grand Line to find the One Piece treasure and make Luffy the next Pirate King.",
    trending: false,
    featured: false,
    subs: 1140,
    dubs: 1133,
    type: 'TV Series'
  },
  {
    id: 4,
    title: "Jujutsu Kaisen",
    japanese: "呪術廻戦",
    poster: "https://picsum.photos/seed/jjk-poster/300/450",
    banner: "https://picsum.photos/seed/jjk-banner/1200/400",
    rating: 8.6,
    year: 2020,
    status: "Ongoing",
    episodes: 47,
    duration: "24 min",
    genre: ["Action", "School", "Supernatural"],
    description: "Yuji Itadori joins Tokyo Jujutsu High School to fight Cursed Spirits after he becomes the host of a powerful Curse named Ryomen Sukuna.",
    trending: true,
    featured: true,
    subs: 47,
    dubs: 47,
    type: 'TV Series'
  },
  {
    id: 5,
    title: "My Hero Academia",
    japanese: "僕のヒーローアカデミア",
    poster: "https://picsum.photos/seed/mha-poster/300/450",
    banner: "https://picsum.photos/seed/mha-banner/1200/400",
    rating: 8.1,
    year: 2016,
    status: "Ongoing",
    episodes: 138,
    duration: "24 min",
    genre: ["Action", "School", "Super Power"],
    description: "In a world where 80% of people have superpowers called 'Quirks', Izuku Midoriya dreams of becoming a hero despite being born without powers.",
    trending: true,
    featured: false,
    subs: 138,
    dubs: 138,
    type: 'TV Series'
  },
  {
    id: 6,
    title: "Naruto",
    japanese: "ナルト",
    poster: "https://picsum.photos/seed/naruto-poster/300/450",
    banner: "https://picsum.photos/seed/naruto-banner/1200/400",
    rating: 8.4,
    year: 2002,
    status: "Completed",
    episodes: 220,
    duration: "23 min",
    genre: ["Action", "Martial Arts", "Comedy"],
    description: "Naruto Uzumaki, a young ninja with a sealed demon fox, dreams of becoming Hokage and gaining the respect of his village through determination.",
    trending: false,
    featured: false,
    subs: 220,
    dubs: 220,
    type: 'TV Series'
  },
  {
    id: 7,
    title: "Steins;Gate",
    japanese: "シュタインズ・ゲート",
    poster: "https://picsum.photos/seed/sg-poster/300/450",
    banner: "https://picsum.photos/seed/sg-banner/1200/400",
    rating: 9.1,
    year: 2011,
    status: "Completed",
    episodes: 24,
    duration: "24 min",
    genre: ["Sci-Fi", "Thriller", "Psychological"],
    description: "A group of friends who have customized their microwave into a device that can send text messages to the past find themselves in a world of conspiracy and danger.",
    trending: false,
    featured: true,
    subs: 24,
    dubs: 24,
    type: 'Movie'
  },
  {
    id: 8,
    title: "Vinland Saga",
    japanese: "ヴィンランド・サガ",
    poster: "https://picsum.photos/seed/vs-poster/300/450",
    banner: "https://picsum.photos/seed/vs-banner/1200/400",
    rating: 8.8,
    year: 2019,
    status: "Ongoing",
    episodes: 48,
    duration: "24 min",
    genre: ["Action", "Adventure", "Historical", "Seinen"],
    description: "Young Thorfinn joins the mercenary band of his father's killer, Askeladd, in hopes of seeking revenge while also dreaming of a peaceful land called Vinland.",
    trending: true,
    featured: false,
    subs: 48,
    dubs: 48,
    type: 'TV Series'
  },
  {
    id: 9,
    title: "Fullmetal Alchemist: Brotherhood",
    japanese: "鋼の錬金術師",
    poster: "https://picsum.photos/seed/fmab-poster/300/450",
    banner: "https://picsum.photos/seed/fmab-banner/1200/400",
    rating: 9.15,
    year: 2009,
    status: "Completed",
    episodes: 64,
    duration: "24 min",
    genre: ["Action", "Adventure", "Fantasy"],
    description: "Two brothers search for the Philosopher's Stone after an attempt to revive their mother goes awry.",
    trending: false,
    featured: true,
    subs: 64,
    dubs: 64,
    type: 'TV Series'
  },
  {
    id: 10,
    title: "Hunter x Hunter (2011)",
    japanese: "ハンター×ハンター",
    poster: "https://picsum.photos/seed/hxh-poster/300/450",
    banner: "https://picsum.photos/seed/hxh-banner/1200/400",
    rating: 9.05,
    year: 2011,
    status: "Completed",
    episodes: 148,
    duration: "23 min",
    genre: ["Action", "Adventure", "Fantasy"],
    description: "Gon Freecss aims to become a Hunter in hopes of finding his father.",
    trending: true,
    featured: false,
    subs: 148,
    dubs: 148,
    type: 'TV Series'
  },
  {
    id: 11,
    title: "Code Geass",
    japanese: "コードギアス 反逆のルルーシュ",
    poster: "https://picsum.photos/seed/cg-poster/300/450",
    banner: "https://picsum.photos/seed/cg-banner/1200/400",
    rating: 8.7,
    year: 2006,
    status: "Completed",
    episodes: 50,
    duration: "24 min",
    genre: ["Action", "Mecha", "Sci-Fi"],
    description: "A high school student gains a power known as Geass and leads a rebellion against a tyrannical empire.",
    trending: false,
    featured: false,
    subs: 50,
    dubs: 50,
    type: 'TV Series'
  },
  {
    id: 12,
    title: "Death Note",
    japanese: "デスノート",
    poster: "https://picsum.photos/seed/dn-poster/300/450",
    banner: "https://picsum.photos/seed/dn-banner/1200/400",
    rating: 8.6,
    year: 2006,
    status: "Completed",
    episodes: 37,
    duration: "23 min",
    genre: ["Supernatural", "Thriller", "Psychological"],
    description: "A high school student discovers a supernatural notebook that allows him to kill anyone by writing their name in it.",
    trending: false,
    featured: false,
    subs: 37,
    dubs: 37,
    type: 'TV Series'
  },
  {
    id: 13,
    title: "Cowboy Bebop",
    japanese: "カウボーイビバップ",
    poster: "https://picsum.photos/seed/cb-poster/300/450",
    banner: "https://picsum.photos/seed/cb-banner/1200/400",
    rating: 8.77,
    year: 1998,
    status: "Completed",
    episodes: 26,
    duration: "24 min",
    genre: ["Action", "Adventure", "Sci-Fi"],
    description: "The futuristic misadventures of a bounty hunter crew on their spaceship, the Bebop.",
    trending: false,
    featured: false,
    subs: 26,
    dubs: 26,
    type: 'Movie'
  },
  {
    id: 14,
    title: "One-Punch Man",
    japanese: "ワンパンマン",
    poster: "https://picsum.photos/seed/opm-poster/300/450",
    banner: "https://picsum.photos/seed/opm-banner/1200/400",
    rating: 8.5,
    year: 2015,
    status: "Ongoing",
    episodes: 24,
    duration: "24 min",
    genre: ["Action", "Comedy", "Super Power"],
    description: "The story of Saitama, a hero who can defeat any opponent with a single punch but seeks to find a worthy opponent.",
    trending: true,
    featured: false,
    subs: 24,
    dubs: 24,
    type: 'TV Series'
  },
  {
    id: 15,
    title: "Mob Psycho 100",
    japanese: "モブサイコ100",
    poster: "https://picsum.photos/seed/mp100-poster/300/450",
    banner: "https://picsum.photos/seed/mp100-banner/1200/400",
    rating: 8.45,
    year: 2016,
    status: "Completed",
    episodes: 37,
    duration: "24 min",
    genre: ["Action", "Comedy", "Supernatural"],
    description: "A middle school boy with psychic powers tries to control his abilities while navigating everyday life.",
    trending: false,
    featured: false,
    subs: 37,
    dubs: 37,
    type: 'TV Series'
  },
  {
    id: 16,
    title: "Haikyuu!!",
    japanese: "ハイキュー!!",
    poster: "https://picsum.photos/seed/hq-poster/300/450",
    banner: "https://picsum.photos/seed/hq-banner/1200/400",
    rating: 8.5,
    year: 2014,
    status: "Completed",
    episodes: 85,
    duration: "24 min",
    genre: ["Comedy", "Sports", "School"],
    description: "A short high school student's journey to become a great volleyball player, despite his height.",
    trending: false,
    featured: false,
    subs: 85,
    dubs: 85,
    type: 'TV Series'
  },
  {
    id: 17,
    title: "Bleach",
    japanese: "ブリーチ",
    poster: "https://picsum.photos/seed/bleach-poster/300/450",
    banner: "https://picsum.photos/seed/bleach-banner/1200/400",
    rating: 7.9,
    year: 2004,
    status: "Completed",
    episodes: 366,
    duration: "24 min",
    genre: ["Action", "Adventure", "Supernatural"],
    description: "Ichigo Kurosaki obtains the powers of a Soul Reaper and takes on the duty of defending humans from evil spirits.",
    trending: false,
    featured: false,
    subs: 366,
    dubs: 366,
    type: 'TV Series'
  },
  {
    id: 18,
    title: "Tokyo Ghoul",
    japanese: "東京喰種-トーキョーグール-",
    poster: "https://picsum.photos/seed/tg-poster/300/450",
    banner: "https://picsum.photos/seed/tg-banner/1200/400",
    rating: 7.8,
    year: 2014,
    status: "Completed",
    episodes: 48,
    duration: "24 min",
    genre: ["Action", "Horror", "Psychological"],
    description: "A college student is transformed into a half-ghoul and must learn to survive in a world where ghouls live among humans.",
    trending: false,
    featured: false,
    subs: 48,
    dubs: 48,
    type: 'TV Series'
  },
  {
    id: 19,
    title: "Psycho-Pass",
    japanese: "サイコパス",
    poster: "https://picsum.photos/seed/pp-poster/300/450",
    banner: "https://picsum.photos/seed/pp-banner/1200/400",
    rating: 8.35,
    year: 2012,
    status: "Ongoing",
    episodes: 41,
    duration: "23 min",
    genre: ["Action", "Sci-Fi", "Police"],
    description: "In a futuristic Japan, the Sibyl System can measure a person's criminal potential, which determines their fate.",
    trending: false,
    featured: false,
    subs: 41,
    dubs: 41,
    type: 'Movie'
  },
  {
    id: 20,
    title: "Neon Genesis Evangelion",
    japanese: "新世紀エヴァンゲリオン",
    poster: "https://picsum.photos/seed/nge-poster/300/450",
    banner: "https://picsum.photos/seed/nge-banner/1200/400",
    rating: 8.32,
    year: 1995,
    status: "Completed",
    episodes: 26,
    duration: "24 min",
    genre: ["Action", "Mecha", "Psychological"],
    description: "A teenage boy is recruited to pilot a giant bio-machine to fight against monstrous beings called Angels.",
    trending: false,
    featured: false,
    subs: 26,
    dubs: 26,
    type: 'TV Series'
  },
  {
    id: 21,
    title: "Re:Zero",
    japanese: "Re:ゼロから始める異世界生活",
    poster: "https://picsum.photos/seed/rz-poster/300/450",
    banner: "https://picsum.photos/seed/rz-banner/1200/400",
    rating: 8.2,
    year: 2016,
    status: "Ongoing",
    episodes: 50,
    duration: "25 min",
    genre: ["Drama", "Fantasy", "Psychological"],
    description: "A boy transported to another world discovers he has the ability to reverse time by dying.",
    trending: true,
    featured: false,
    subs: 50,
    dubs: 50,
    type: 'TV Series'
  },
  {
    id: 22,
    title: "Chainsaw Man",
    japanese: "チェンソーマン",
    poster: "https://picsum.photos/seed/csm-poster/300/450",
    banner: "https://picsum.photos/seed/csm-banner/1200/400",
    rating: 8.8,
    year: 2022,
    status: "Ongoing",
    episodes: 12,
    duration: "24 min",
    genre: ["Action", "Supernatural", "Gore"],
    description: "A young man who hunts devils makes a contract with his devil pet to be resurrected as 'Chainsaw Man'.",
    trending: true,
    featured: true,
    subs: 12,
    dubs: 12,
    type: 'TV Series'
  },
  {
    id: 23,
    title: "Dr. Stone",
    japanese: "ドクターストーン",
    poster: "https://picsum.photos/seed/drs-poster/300/450",
    banner: "https://picsum.photos/seed/drs-banner/1200/400",
    rating: 8.3,
    year: 2019,
    status: "Ongoing",
    episodes: 46,
    duration: "24 min",
    genre: ["Adventure", "Sci-Fi", "Comedy"],
    description: "A scientific genius awakens in a world where humanity has been petrified and aims to rebuild civilization with science.",
    trending: false,
    featured: false,
    subs: 46,
    dubs: 46,
    type: 'TV Series'
  },
  {
    id: 24,
    title: "Mushoku Tensei: Jobless Reincarnation",
    japanese: "無職転生 〜異世界行ったら本気だす〜",
    poster: "https://picsum.photos/seed/mt-poster/300/450",
    banner: "https://picsum.photos/seed/mt-banner/1200/400",
    rating: 8.4,
    year: 2021,
    status: "Ongoing",
    episodes: 35,
    duration: "23 min",
    genre: ["Drama", "Fantasy", "Isekai"],
    description: "A 34-year-old shut-in is reincarnated into a fantasy world with his memories intact and resolves to live his new life to the fullest.",
    trending: true,
    featured: false,
    subs: 35,
    dubs: 35,
    type: 'TV Series'
  },
  {
    id: 25,
    title: "The Promised Neverland",
    japanese: "約束のネバーランド",
    poster: "https://picsum.photos/seed/tpn-poster/300/450",
    banner: "https://picsum.photos/seed/tpn-banner/1200/400",
    rating: 8.5,
    year: 2019,
    status: "Completed",
    episodes: 23,
    duration: "22 min",
    genre: ["Mystery", "Thriller", "Supernatural"],
    description: "A group of gifted orphans discover the dark truth about their seemingly idyllic orphanage and plot an escape.",
    trending: false,
    featured: false,
    subs: 23,
    dubs: 23,
    type: 'TV Series'
  },
  {
    id: 26,
    title: "Bocchi the Rock!",
    japanese: "ぼっち・ざ・ろっく！",
    poster: "https://picsum.photos/seed/btr-poster/300/450",
    banner: "https://picsum.photos/seed/btr-banner/1200/400",
    rating: 9.0,
    year: 2022,
    status: "Completed",
    episodes: 12,
    duration: "23 min",
    genre: ["Comedy", "Music", "Slice of Life"],
    description: "A socially anxious girl who is a talented guitarist is recruited into a band and must overcome her fears.",
    trending: false,
    featured: false,
    subs: 12,
    dubs: 12,
    type: 'TV Series'
  },
  {
    id: 27,
    title: "Made in Abyss",
    japanese: "メイドインアビス",
    poster: "https://picsum.photos/seed/mia-poster/300/450",
    banner: "https://picsum.photos/seed/mia-banner/1200/400",
    rating: 8.4,
    year: 2017,
    status: "Ongoing",
    episodes: 25,
    duration: "25 min",
    genre: ["Adventure", "Dark Fantasy", "Mystery"],
    description: "A young girl and a robot boy descend into a mysterious, chasm-like Abyss in search of her mother.",
    trending: false,
    featured: false,
    subs: 25,
    dubs: 25,
    type: 'Movie'
  },
  {
    id: 28,
    title: "Parasyte: The Maxim",
    japanese: "寄生獣 セイの格率",
    poster: "https://picsum.photos/seed/ptm-poster/300/450",
    banner: "https://picsum.photos/seed/ptm-banner/1200/400",
    rating: 8.4,
    year: 2014,
    status: "Completed",
    episodes: 24,
    duration: "23 min",
    genre: ["Action", "Horror", "Sci-Fi"],
    description: "A high school student's right hand is infected with a parasite, and they form an unlikely alliance to survive.",
    trending: false,
    featured: false,
    subs: 24,
    dubs: 24,
    type: 'TV Series'
  },
  {
    id: 29,
    title: "Your Lie in April",
    japanese: "四月は君の嘘",
    poster: "https://picsum.photos/seed/yla-poster/300/450",
    banner: "https://picsum.photos/seed/yla-banner/1200/400",
    rating: 8.7,
    year: 2014,
    status: "Completed",
    episodes: 22,
    duration: "22 min",
    genre: ["Drama", "Music", "Romance"],
    description: "A piano prodigy who has lost his ability to play meets a free-spirited violinist who changes his life.",
    trending: false,
    featured: false,
    subs: 22,
    dubs: 22,
    type: 'TV Series'
  },
  {
    id: 30,
    title: "Anohana: The Flower We Saw That Day",
    japanese: "あの日見た花の名前を僕達はまだ知らない。",
    poster: "https://picsum.photos/seed/anohana-poster/300/450",
    banner: "https://picsum.photos/seed/anohana-banner/1200/400",
    rating: 8.3,
    year: 2011,
    status: "Completed",
    episodes: 11,
    duration: "22 min",
    genre: ["Drama", "Slice of Life", "Supernatural"],
    description: "A group of estranged childhood friends is reunited by the ghost of their friend who died years ago.",
    trending: false,
    featured: false,
    subs: 11,
    dubs: 11,
    type: 'Movie'
  }
];