import { Anime } from './types';

export const animeDatabase: Anime[] = [
  {
    id: 1,
    title: "Attack on Titan",
    japanese: "進撃の巨人",
    poster: "https://picsum.photos/seed/aot-poster/300/450",
    banner: "https://picsum.photos/seed/aot-banner/1200/400",
    rating: 9.0,
    year: 2013,
    status: "Completed",
    episodes: 87,
    duration: "24 min",
    genre: ["Action", "Drama", "Fantasy"],
    description: "Humanity fights for survival against giant humanoid Titans. When a colossal Titan breaches their wall, Eren Yeager joins the Survey Corps to fight back.",
    trending: true,
    featured: true
  },
  {
    id: 2,
    title: "Demon Slayer",
    japanese: "鬼滅の刃",
    poster: "https://picsum.photos/seed/ds-poster/300/450",
    banner: "https://picsum.photos/seed/ds-banner/1200/400",
    rating: 8.7,
    year: 2019,
    status: "Ongoing",
    episodes: 44,
    duration: "23 min",
    genre: ["Action", "Supernatural", "Historical"],
    description: "After his family is slaughtered by demons, Tanjiro Kamado embarks on a dangerous journey to turn his demon sister back into a human.",
    trending: true,
    featured: false
  },
  {
    id: 3,
    title: "One Piece",
    japanese: "ワンピース",
    poster: "https://picsum.photos/seed/op-poster/300/450",
    banner: "https://picsum.photos/seed/op-banner/1200/400",
    rating: 9.2,
    year: 1999,
    status: "Ongoing",
    episodes: 1075,
    duration: "24 min",
    genre: ["Adventure", "Comedy", "Shounen"],
    description: "Follow Monkey D. Luffy and his Straw Hat Pirates as they explore the Grand Line to find the One Piece treasure and make Luffy the next Pirate King.",
    trending: false,
    featured: false
  },
  {
    id: 4,
    title: "Jujutsu Kaisen",
    japanese: "呪術廻戦",
    poster: "https://picsum.photos/seed/jjk-poster/300/450",
    banner: "https://picsum.photos/seed/jjk-banner/1200/400",
    rating: 8.6,
    year: 2020,
    status: "Ongoing",
    episodes: 47,
    duration: "24 min",
    genre: ["Action", "School", "Supernatural"],
    description: "Yuji Itadori joins Tokyo Jujutsu High School to fight Cursed Spirits after he becomes the host of a powerful Curse named Ryomen Sukuna.",
    trending: true,
    featured: true
  },
  {
    id: 5,
    title: "My Hero Academia",
    japanese: "僕のヒーローアカデミア",
    poster: "https://picsum.photos/seed/mha-poster/300/450",
    banner: "https://picsum.photos/seed/mha-banner/1200/400",
    rating: 8.1,
    year: 2016,
    status: "Ongoing",
    episodes: 138,
    duration: "24 min",
    genre: ["Action", "School", "Super Power"],
    description: "In a world where 80% of people have superpowers called 'Quirks', Izuku Midoriya dreams of becoming a hero despite being born without powers.",
    trending: true,
    featured: false
  },
  {
    id: 6,
    title: "Naruto",
    japanese: "ナルト",
    poster: "https://picsum.photos/seed/naruto-poster/300/450",
    banner: "https://picsum.photos/seed/naruto-banner/1200/400",
    rating: 8.4,
    year: 2002,
    status: "Completed",
    episodes: 220,
    duration: "23 min",
    genre: ["Action", "Martial Arts", "Comedy"],
    description: "Naruto Uzumaki, a young ninja with a sealed demon fox, dreams of becoming Hokage and gaining the respect of his village through determination.",
    trending: false,
    featured: false
  },
  {
    id: 7,
    title: "Steins;Gate",
    japanese: "シュタインズ・ゲート",
    poster: "https://picsum.photos/seed/sg-poster/300/450",
    banner: "https://picsum.photos/seed/sg-banner/1200/400",
    rating: 9.1,
    year: 2011,
    status: "Completed",
    episodes: 24,
    duration: "24 min",
    genre: ["Sci-Fi", "Thriller", "Psychological"],
    description: "A group of friends who have customized their microwave into a device that can send text messages to the past find themselves in a world of conspiracy and danger.",
    trending: false,
    featured: true
  },
  {
    id: 8,
    title: "Vinland Saga",
    japanese: "ヴィンランド・サガ",
    poster: "https://picsum.photos/seed/vs-poster/300/450",
    banner: "https://picsum.photos/seed/vs-banner/1200/400",
    rating: 8.8,
    year: 2019,
    status: "Ongoing",
    episodes: 48,
    duration: "24 min",
    genre: ["Action", "Adventure", "Historical", "Seinen"],
    description: "Young Thorfinn joins the mercenary band of his father's killer, Askeladd, in hopes of seeking revenge while also dreaming of a peaceful land called Vinland.",
    trending: true,
    featured: false
  }
];
