import { Anime } from './types';

export const animeDatabase: Anime[] = [
  {
    id: "1",
    slug: "attack-on-titan",
    titleEN: "Attack on Titan",
    titleJP: "進撃の巨人",
    poster: "https://picsum.photos/seed/aot-poster/300/450",
    banner: "https://picsum.photos/seed/aot-banner/1200/400",
    year: 2013,
    status: "Completed",
    type: 'TV Series',
    genres: ["Action", "Drama", "Fantasy"],
    synopsis: "Humanity fights for survival against giant humanoid Titans. When a colossal Titan breaches their wall, Eren Yeager joins the Survey Corps to fight back.",
    availableAudios: ['hi', 'en', 'ja'],
    episodes: Array.from({ length: 87 }, (_, i) => ({
      id: `aot-ep-${i + 1}`,
      number: i + 1,
      slug: `episode-${i + 1}`,
      mediaId: `aot-media-${i + 1}`,
      durationSec: 1440,
      availableAudios: ['hi', 'en', 'ja'],
    })),
  },
  {
    id: "2",
    slug: "demon-slayer",
    titleEN: "Demon Slayer",
    titleJP: "鬼滅の刃",
    poster: "https://picsum.photos/seed/ds-poster/300/450",
    banner: "https://picsum.photos/seed/ds-banner/1200/400",
    year: 2019,
    status: "Ongoing",
    type: 'TV Series',
    genres: ["Action", "Supernatural", "Historical"],
    synopsis: "After his family is slaughtered by demons, Tanjiro Kamado embarks on a dangerous journey to turn his demon sister back into a human.",
    availableAudios: ['hi', 'en'],
    episodes: Array.from({ length: 44 }, (_, i) => ({
      id: `ds-ep-${i + 1}`,
      number: i + 1,
      slug: `episode-${i + 1}`,
      mediaId: `ds-media-${i + 1}`,
      durationSec: 1380,
      availableAudios: ['hi', 'en'],
    })),
  },
  {
    id: "3",
    slug: "one-piece",
    titleEN: "One Piece",
    titleJP: "ワンピース",
    poster: "https://picsum.photos/seed/op-poster/300/450",
    banner: "https://picsum.photos/seed/op-banner/1200/400",
    year: 1999,
    status: "Ongoing",
    type: 'TV Series',
    genres: ["Adventure", "Comedy", "Shounen"],
    synopsis: "Follow Monkey D. Luffy and his Straw Hat Pirates as they explore the Grand Line to find the One Piece treasure and make Luffy the next Pirate King.",
    availableAudios: ['hi', 'en', 'ja'],
    episodes: Array.from({ length: 1075 }, (_, i) => ({
      id: `op-ep-${i + 1}`,
      number: i + 1,
      slug: `episode-${i + 1}`,
      mediaId: `op-media-${i + 1}`,
      durationSec: 1440,
      availableAudios: i < 500 ? ['hi', 'en', 'ja'] : ['en', 'ja'],
    })),
  },
  {
    id: "4",
    slug: "jujutsu-kaisen",
    titleEN: "Jujutsu Kaisen",
    titleJP: "呪術廻戦",
    poster: "https://picsum.photos/seed/jjk-poster/300/450",
    banner: "https://picsum.photos/seed/jjk-banner/1200/400",
    year: 2020,
    status: "Ongoing",
    type: 'TV Series',
    genres: ["Action", "School", "Supernatural"],
    synopsis: "Yuji Itadori joins Tokyo Jujutsu High School to fight Cursed Spirits after he becomes the host of a powerful Curse named Ryomen Sukuna.",
    availableAudios: ['hi', 'en', 'ja'],
    episodes: Array.from({ length: 47 }, (_, i) => ({
      id: `jjk-ep-${i + 1}`,
      number: i + 1,
      slug: `episode-${i + 1}`,
      mediaId: `jjk-media-${i + 1}`,
      durationSec: 1440,
      availableAudios: ['hi', 'en', 'ja'],
    })),
  },
    {
    id: "5",
    slug: "steins-gate",
    titleEN: "Steins;Gate",
    titleJP: "シュタインズ・ゲート",
    poster: "https://picsum.photos/seed/sg-poster/300/450",
    banner: "https://picsum.photos/seed/sg-banner/1200/400",
    year: 2011,
    status: "Completed",
    type: 'Movie',
    genres: ["Sci-Fi", "Thriller", "Psychological"],
    synopsis: "A group of friends who have customized their microwave into a device that can send text messages to the past find themselves in a world of conspiracy and danger.",
    availableAudios: ['hi', 'en'],
     episodes: [{
      id: `sg-ep-1`,
      number: 1,
      slug: `movie`,
      mediaId: `sg-media-1`,
      durationSec: 5400,
      availableAudios: ['hi', 'en'],
    }],
  },
   {
    id: "6",
    slug: "naruto",
    titleEN: "Naruto",
    titleJP: "ナルト",
    poster: "https://picsum.photos/seed/naruto-poster/300/450",
    banner: "https://picsum.photos/seed/naruto-banner/1200/400",
    year: 2002,
    status: "Completed",
    type: 'TV Series',
    genres: ["Action", "Martial Arts", "Comedy"],
    synopsis: "Naruto Uzumaki, a young ninja with a sealed demon fox, dreams of becoming Hokage and gaining the respect of his village through determination.",
    availableAudios: ['hi', 'en', 'ja'],
    episodes: Array.from({ length: 220 }, (_, i) => ({
      id: `naruto-ep-${i + 1}`,
      number: i + 1,
      slug: `episode-${i + 1}`,
      mediaId: `naruto-media-${i + 1}`,
      durationSec: 1380,
      availableAudios: ['hi', 'en', 'ja'],
    })),
  },
];
